### ISSUE TITLE
Redirect url in JWT in regular consent (and PAR) flow is null

### ISSUE THREAD

**Issue by Aiden-Ziegelaar** [ConsumerDataRight/sandbox#11]
**Describe the bug**
When consent JWT is constructed the `redirect_uri` claim is present but `null`.

**To Reproduce**

Parameters for constructing request:
```
{
  "RegistrationId": "bcc3e60cf4b840089f85ed6449f75383|||55567e9f-b27f-4c3b-90c8-298af5ac4bb3"
  "CdrArrangementId": ""
  "SharingDuration": 2140000000
  "Scope": "openid profile common:customer.basic:read common:customer.detail:read energy:electricity.servicepoints.basic:read energy:electricity.servicepoints.detail:read energy:electricity.usage:read energy:electricity.der:read energy:accounts.basic:read energy:accounts.detail:read energy:accounts.paymentschedule:read energy:accounts.concessions:read energy:billing:read common:customer.basic:read"
  "UsePkce": true
}
```

Steps to reproduce the behaviour (old consent):
1. Navigate to https://dr.cdrsandbox.gov.au/consent
2. Construct an authorisation URI
4. Inspect the token in the URL, see that `"redirect_uri": null` is in the claims
5. See error

Steps to reproduce the behaviour (PAR):
1. Navigate to https://dr.cdrsandbox.gov.au/par
2. Initiate PAR 
3. See error stating that `redirect_uri` claim is malformed

**Expected behaviour**
Redirect URI should be correctly populated with the redirect URI registered with the infosec provider, in our case this is: 
`https://dr.cdrsandbox.gov.au/consent/callback`

**Screenshots**
![Screen Shot 2022-09-29 at 09 39 24 am](https://user-images.githubusercontent.com/19164243/192919025-8128d5ea-2dfe-4627-a689-e1a6a4794f75.png)

**Additional context**
Example Token:
```
eyJhbGciOiJQUzI1NiIsImtpZCI6IjdFRkE4NUMxOEZERTg1Nzk0OUJDMkVBQTIxQzI1RTQ5NjI3RDQ4NjUiLCJ4NXQiOiJmdnFGd1lfZWhYbEp2QzZxSWNKZVNXSjlTR1UiLCJ0eXAiOiJKV1QifQ.eyJyZXNwb25zZV90eXBlIjoiY29kZSBpZF90b2tlbiIsImNsaWVudF9pZCI6ImJjYzNlNjBjZjRiODQwMDg5Zjg1ZWQ2NDQ5Zjc1MzgzIiwicmVkaXJlY3RfdXJpIjpudWxsLCJyZXNwb25zZV9tb2RlIjoiZm9ybV9wb3N0Iiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBjb21tb246Y3VzdG9tZXIuYmFzaWM6cmVhZCBjb21tb246Y3VzdG9tZXIuZGV0YWlsOnJlYWQgZW5lcmd5OmVsZWN0cmljaXR5LnNlcnZpY2Vwb2ludHMuYmFzaWM6cmVhZCBlbmVyZ3k6ZWxlY3RyaWNpdHkuc2VydmljZXBvaW50cy5kZXRhaWw6cmVhZCBlbmVyZ3k6ZWxlY3RyaWNpdHkudXNhZ2U6cmVhZCBlbmVyZ3k6ZWxlY3RyaWNpdHkuZGVyOnJlYWQgZW5lcmd5OmFjY291bnRzLmJhc2ljOnJlYWQgZW5lcmd5OmFjY291bnRzLmRldGFpbDpyZWFkIGVuZXJneTphY2NvdW50cy5wYXltZW50c2NoZWR1bGU6cmVhZCBlbmVyZ3k6YWNjb3VudHMuY29uY2Vzc2lvbnM6cmVhZCBlbmVyZ3k6YmlsbGluZzpyZWFkIGNvbW1vbjpjdXN0b21lci5iYXNpYzpyZWFkIiwic3RhdGUiOiIyZDgwNjBkMS01ZjUwLTQ5ZGMtYjRiZi0yMzNlZjYxODUyYTUiLCJub25jZSI6IjkzMTE0MGFkLTNlNTAtNDE3ZS1hY2E1LWM4MzE0MDZkZjFjZCIsImNsYWltcyI6eyJzaGFyaW5nX2R1cmF0aW9uIjoyMTQwMDAwMDAwLCJjZHJfYXJyYW5nZW1lbnRfaWQiOm51bGwsInVzZXJpbmZvIjp7ImdpdmVuX25hbWUiOm51bGwsImZhbWlseV9uYW1lIjpudWxsfSwiaWRfdG9rZW4iOnsiYWNyIjp7ImVzc2VudGlhbCI6dHJ1ZSwidmFsdWVzIjpbInVybjpjZHMuYXU6Y2RyOjMiXX19fSwiY29kZV9jaGFsbGVuZ2UiOiJ1by1zLUdvSjR2YkZBY0x6emNidDhXM0lJVU15RzhVWW5KY2hqOGJoRm1RIiwiY29kZV9jaGFsbGVuZ2VfbWV0aG9kIjoiUzI1NiIsIm5iZiI6MTY2NDQxNDQ1OSwiZXhwIjoxNjY0NDE0NzU5LCJpYXQiOjE2NjQ0MTQ0NTksImlzcyI6ImJjYzNlNjBjZjRiODQwMDg5Zjg1ZWQ2NDQ5Zjc1MzgzIiwiYXVkIjoiaHR0cHM6Ly9hdXRobmNkci10ZXN0LmVuZXJneWF1c3RyYWxpYS5jb20uYXUvZW5lcmd5YXVzdHJhbGlhLWNkciJ9.Mjl5v1Cz_TEbktzPCaTYNN8fLdNgdx8J5FanzbuhqhI1fXQTcKIZjVwLsBo38DcknqWUN2zK__BxKQ_qP-aeun9WFBg62jMyi1P8GL33bAB_xWfW7f0C5FueXZe1uaUGd8rtYHZEY14Qavq0pNSeHKp2GUvn7u_oFAKhKAecTE5Xi_7udNjELLhDKLiJgOF-iuPi_RdawAeXhwDflzfQJYrmIhih3Y_QTENdjLXmJuGiFrrmwqQm_CDaAGS7HXmCh2pJQwonECyQcoM7JGiYzEpL3CNcHwuBWWXBZ31simNbd79wBdYeG9UKqh_b-NPsL2pSNE0F7wUePzh8PYp_YweyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
```

**Comment by CDR-AndrewG** [comment]
Hi @Aiden-Ziegelaar,

Thank you for raising this issue. We are currently investigating to find where the error is occurring.

**Comment by CDR-AndrewG** [comment]
Hi @Aiden-Ziegelaar,

We are still investigating the issue. Providing this update in case it is useful for you. 

There was a different error occurring when we were trying to replicate the issue. The other issue has been resolved. 

With the other issue out of the way, we have noticed that from both the PAR and Consents page the authorise Uri is being returned and displayed.

We are using EnergyAustralia-TEST (55567e9f-b27f-4c3b-90c8-298af5ac4bb3)

![image](https://user-images.githubusercontent.com/89497569/193985186-66461428-a44f-4905-b843-b2589623c131.png)

**Comment by Aiden-Ziegelaar** [comment]
@CDR-AndrewG thanks for the update!

Testing against `dr.cdrsandbox.gov.au/consent` and `https://dr.cdrsandbox.gov.au/par` I'm still receiving the same error.

**Comment by Aiden-Ziegelaar** [comment]
It only seems to present with the following scopes:
`openid profile common:customer.basic:read common:customer.detail:read energy:electricity.servicepoints.basic:read energy:electricity.servicepoints.detail:read energy:electricity.usage:read energy:electricity.der:read energy:accounts.basic:read energy:accounts.detail:read energy:accounts.paymentschedule:read energy:accounts.concessions:read energy:billing:read`

I'm not sure exactly which scope is causing the issue.

**Comment by CDR-AndrewG** [comment]
Hi @Aiden-Ziegelaar,

This issue should be resolved in the latest release of the Sandbox which went out yesterday. We could not replicate the issue consistently. We made some changes to how the redirect_uri is shared between the UI and API to reduce the chance that this issue is caused by an intermittent javascript error.

Let me know if this issue occurs for you again and we'll have another look.

**Comment by Aiden-Ziegelaar** [comment]
Looks like this issue should be good to close now, we're no longer experiencing this behaviour.
